{extends ../layout.phtml}

{block #header}
<script src="{$baseUri}js/jquery.min.js" type="text/javascript"></script>
<script src="{$baseUri}js/jquery.nivo.slider.pack.js" type="text/javascript"></script>
<link rel="stylesheet" href="{$baseUri}css/frontend2012.css" type="text/css" media="screen" />
<link rel="stylesheet" href="{$baseUri}css/nivo-slider.css" type="text/css" media="screen" />
<script type="text/javascript">
	$(window).load(function() {
		$('#slider').nivoSlider({
			effect:'fade',
			pauseTime:3000,
			captionOpacity:1,
			directionNav:true,
			controlNav:false
		});
	});
</script>
{/block}

{block #body}
	{block #content}{/block}
{/block}